name: classipod
description: "A ipod Classic Emulator"

publish_to: 'none'

version: 1.10.1+23

environment:
  sdk: ^3.7.0
  flutter: 3.32.4

dependencies:
  audio_metadata_reader: ^1.4.1
  audio_service: ^0.18.18
  battery_plus: ^6.2.1
  cupertino_icons: ^1.0.8
  device_preview_plus: ^2.4.2
  disable_battery_optimization:
    git:
      url: https://github.com/adeeteya/Disable-Battery-Optimizations.git
      ref: master
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: any
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.17
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_windows_audio: ^1.0.9
  on_audio_query:
    git:
      url: https://github.com/adeeteya/on_audio_query.git
      ref: main
      path: packages/on_audio_query
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  tutorial_coach_mark: ^1.3.0
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  vibration_web: ^1.6.8
  volume_controller: ^3.4.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.2
  riverpod_lint: ^2.6.5

dependency_overrides:
  intl: 0.20.2
  just_audio: 0.10.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700