name: retropod
description: "A ipod Classic Emulator"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  flutter_svg: ^2.0.9
  battery_plus: ^5.0.2
  permission_handler: ^11.2.0
  flutter_media_metadata: ^1.0.0+1
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: false

  assets:
   - assets/
   - assets/fonts/
   - assets/icons/
   - assets/images/

  fonts:
   - family: Myriad
     fonts:
       - asset: assets/fonts/Myriad-Regular.ttf
       - asset: assets/fonts/Myriad-Bold.ttf
         weight: 700

   - family: SF Pro Text
     fonts:
       - asset: assets/fonts/SFProText-Bold.otf
         weight: 700