name: classipod
description: "A ipod Classic Emulator"

publish_to: 'none'

version: 1.5.0+7

environment:
  sdk: ^3.6.1
  flutter: 3.27.3

dependencies:
  audio_metadata_reader: ^1.1.0
  battery_plus: ^6.2.1
  cupertino_icons: ^1.0.8
  device_preview_plus: ^2.2.5
  disable_battery_optimization: ^1.1.1
  file_picker: ^8.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.2
  intl: any
  just_audio: ^0.9.44
  just_audio_background: ^0.0.1-beta.14
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.1
  tutorial_coach_mark: ^1.2.12
  url_launcher: ^6.3.1
  vibration: ^3.1.2

dev_dependencies:
  custom_lint: ^0.7.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.4

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/
   - assets/fonts/
   - assets/images/

  fonts:
   - family: Myriad
     fonts:
       - asset: assets/fonts/Myriad-Regular.ttf
       - asset: assets/fonts/Myriad-Bold.ttf
         weight: 700

   - family: SF Pro Text
     fonts:
       - asset: assets/fonts/SFProText-Bold.otf
         weight: 700