name: classipod
description: "A ipod Classic Emulator"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  audio_service: ^0.18.13
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.11
  flutter_svg: ^2.0.10+1
  battery_plus: ^6.0.1
  permission_handler: ^11.3.1
  flutter_media_metadata: ^1.0.0+1
  go_router: ^14.1.1
  vibration: ^1.8.4
  file_picker: ^8.0.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false

  assets:
   - assets/
   - assets/fonts/
   - assets/icons/
   - assets/images/

  fonts:
   - family: Myriad
     fonts:
       - asset: assets/fonts/Myriad-Regular.ttf
       - asset: assets/fonts/Myriad-Bold.ttf
         weight: 700

   - family: SF Pro Text
     fonts:
       - asset: assets/fonts/SFProText-Bold.otf
         weight: 700