name: classipod
description: "A ipod Classic Emulator"

publish_to: 'none'

version: 1.7.5+13

environment:
  sdk: ^3.7.0
  flutter: 3.29.0

dependencies:
  audio_metadata_reader: ^1.1.0
  battery_plus: ^6.2.1
  cupertino_icons: ^1.0.8
  device_preview_plus: ^2.2.7
  disable_battery_optimization:
    git:
      url: https://github.com/adeeteya/Disable-Battery-Optimizations.git
      ref: master
  file_picker: ^9.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  intl: any
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  tutorial_coach_mark: ^1.2.12
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  vibration_web: ^1.6.8

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.2
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/Myriad-Regular.ttf
        - asset: assets/fonts/Myriad-Bold.ttf
          weight: 700

    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProText-Bold.otf
          weight: 700