name: classipod
description: "A ipod Classic Emulator"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  flutter_svg: ^2.0.10+1
  battery_plus: ^5.0.3
  permission_handler: ^11.3.0
  flutter_media_metadata: ^1.0.0+1
  go_router: ^13.2.1
  vibration: ^1.8.4
  file_picker: ^6.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: false

  assets:
   - assets/
   - assets/fonts/
   - assets/icons/
   - assets/images/

  fonts:
   - family: Myriad
     fonts:
       - asset: assets/fonts/Myriad-Regular.ttf
       - asset: assets/fonts/Myriad-Bold.ttf
         weight: 700

   - family: SF Pro Text
     fonts:
       - asset: assets/fonts/SFProText-Bold.otf
         weight: 700