name: classipod
description: "A ipod Classic Emulator"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.5
  just_audio: ^0.9.42
  battery_plus: ^6.2.1
  permission_handler: ^11.3.1
  go_router: ^14.6.2
  vibration: ^2.0.1
  file_picker: ^8.1.7
  url_launcher: ^6.3.1
  vector_graphics: ^1.1.15
  audio_metadata_reader: ^1.1.0
  just_audio_background: ^0.0.1-beta.14
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  vector_graphics_compiler: ^1.1.16

dependency_overrides:
  audio_metadata_reader: 0.0.5

flutter:
  uses-material-design: false

  assets:
   - assets/
   - assets/fonts/
   - assets/images/
   - path: assets/icons/
     transformers:
       - package: vector_graphics_compiler

  fonts:
   - family: Myriad
     fonts:
       - asset: assets/fonts/Myriad-Regular.ttf
       - asset: assets/fonts/Myriad-Bold.ttf
         weight: 700

   - family: SF Pro Text
     fonts:
       - asset: assets/fonts/SFProText-Bold.otf
         weight: 700