display_name: Classipod
package_name: classipod
maintainer:
  name: Aditya
  email: adeeteya@gmail.com
priority: optional
section: x11
installed_size: 9280
essential: false
icon: snap/gui/classipod.png

dependencies:
  - mpv
  - libmpv1
  - libmpv-dev

postinstall_scripts:
  - echo "Thanks for installing Classipod. If you like the app please give it a star on GitHub"
postuninstall_scripts:
  - echo "Sorry to see you go. If there are problems in the app please open an issue on GitHub"

keywords:
  - Music
  - Audio
  - iPod
  - Local
  - Songs
  - Offline

generic_name: Local Music Player

categories:
  - Music

startup_notify: true