name: classipod
version: 1.10.1
summary: Local Music Player Inspired by the iPod Classic
description: ClassiPod is a lightweight, offline music player app that emulates the experience of the legendary iPod Classic. It supports local music playback, shuffle/repeat, custom playlists, cover art, and more — all in a nostalgic design.
icon: snap/gui/classipod.png
contact: mailto:adeeteya@gmail.com
source-code: https://github.com/adeeteya/Classipod
issues: https://github.com/adeeteya/Classipod/issues
license: MIT

confinement: strict
base: core22
grade: stable

slots:
  classipod:
    interface: dbus
    bus: session
    name: com.adeeteya.classipod

apps:
  classipod:
    command: classipod
    extensions: [gnome]
    plugs:
      - audio-playback
      - removable-media
      - desktop
      - home
    slots:
      - classipod
parts:
  classipod:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
